### ISSUE TITLE
可以支持gridview的不同spacing吗

### ISSUE THREAD

**Issue by git-maven** [simplepeng/ItemDecor#1]
像Flutter的mainAxisSpacing crossAxisSpacing
可以支持gridview行跟列的间距自定义

**Comment by simplepeng** [comment]
@git-maven Flutter不是很懂，但是行跟列的间距自定义是可以的，GridItemDecor支持`marginStart `，`marginTop `，`marginBottom `，`marginEnd `，的不同设置
